### PR TITLE
Adding regex as a dependency

### PR DESCRIPTION
**Pull request by LyesSaadi**

### CODE REVIEW

**Comment by 0xMRTT** [comment]
:+1:

**Comment by LyesSaadi** [comment]
Could a new release be sent to pypi?

**Comment by 0xMRTT** [comment]
I think that we can automate the release process using GitHub CI

**Comment by avanisubbiah** [comment]
I've updated the PyPI release

**Comment by avanisubbiah** [comment]
> I think that we can automate the release process using GitHub CI

I looked through some of them. There are Github actions for publishing to PyPI but none seem to be using poetry.

**Pull request merged**
